### ISSUE TITLE
Can I get in touch with you?

### ISSUE THREAD

**Issue by ArtrenH** [Vertretungsapp/app#114]
Unfortunatly, Github has no feature for dms, but I nevertheless want to contact you, because I saw this project and run a similiar website (https://vplan.fr) that displays indiware-data in a much better way and with more features.
If you are interested in getting in touch, please contact me on discord, I am `_qrtrenh`.

**Comment by ArtrenH** [comment]
You can also take a look at our project. You can find the source code in this repo:
https://github.com/ArtrenH/VPlan_FR/

**Comment by SachsenspieltCoding** [comment]
:)
