### ISSUE TITLE
Verbesserung der Wischgesten für die Navigation durch Tage

### ISSUE THREAD

**Issue by annhilati** [Vertretungsapp/app#259]
Aktuell kann man nur mit Pfeilen navigieren. Wäre cool, wenn man es auch mit Wischgesten könnte. Benachbarte Tage am besten preloaden, damit das zackig geht.

**Comment by SachsenspieltCoding** [comment]
> Aktuell kann man nur mit Pfeilen navigieren. Wäre cool, wenn man es auch mit Wischgesten könnte. Benachbarte Tage am besten preloaden, damit das zackig geht.

Hey,
theoretisch sind Wischgesten implementiert. Die sind aber etwas buggy, das ist bekannt. Das sollte auf jeden Fall noch verbessert werden.

Preloading ergibt sich durch den Cache von 14 Tagen (wird später einstellbar sein), welcher jetzt durch die vergangenen Sommerferien natürlich nicht all zu viel speichern kann. Sobald wieder regelmäßig Pläne rauskommen, funktioniert auch alles wieder "zackig"

**Comment by annhilati** [comment]
Das mit dem Preloading bezieht sich vor allem darauf, dass ein Tag gut ¾s geladen hat. Wenn man schnell und einfach navigieren will ist das meiner Erfahrung nach etwas zu langsam. Aber das wird 👍

**Comment by annhilati** [comment]
Auf einem anderen Handy hat's tatsächlich eben noch funktioniert, jetzt nicht mehr

**Comment by SachsenspieltCoding** [comment]
Also bei mir (iOS 18) geht es eigentlich recht zuverlässig. Ich hatte aber auch genügend Leute schon, die auf meinem Gerät selbst Probleme mit den Gesten hatten.

Vermutlich werde ich da nochmal eine andere Library testen müssen, oder gar was ganz eigenens programmieren

**Comment by SachsenspieltCoding** [comment]
@annhilati Ich hab jetzt mal alles ein bisschen empfindlicher eingestellt. Schau es dir am Besten mal an
https://app-git-issue-259-vertretungsapp.vercel.app/

**Comment by annhilati** [comment]
Es klappt bei mir jetzt, aber nur im Header. Also da wo die Stunden aufgelistet sind geht's nicht

**Comment by annhilati** [comment]
Es hat tatsächlich so auch schon auf der aktuellen Version funktioniert

**Comment by SachsenspieltCoding** [comment]
Du nutzt Chrome/Android richtig?

Ich glaube einfach, dass durch diese Scrollbare Stundenanzeige, der die vertikale Gesten nicht mehr richtig tracken kann.
Mal schauen. Ich versuche erstmal das Problem zu reproduzieren, um dann irgendwie eine Lösung zu finden

**Comment by annhilati** [comment]
Chrome
Android 14
HyperOS 1.0.4

**Comment by SachsenspieltCoding** [comment]
Reproduzierbar unter:

Chromium 127.0.6533.88 (Mobile Ansicht)
Zorin OS 17.1

**Comment by SachsenspieltCoding** [comment]
Scheint wohl ein Bug in der `svelte-gestures` Library zu geben, ich habe dort mal ein Issue aufgemacht
https://github.com/Rezi/svelte-gestures/issues/28

**Comment by SachsenspieltCoding** [comment]
@annhilati Das Problem ist jetzt hoffentlich behoben. Könntest du es nochmal testen?
https://app-git-issue-259-vertretungsapp.vercel.app/

**Comment by annhilati** [comment]
Funktioniert einwandfrei
