### ISSUE TITLE
Verbesserungsvorschlag zur Anzeige von Stunden

### ISSUE THREAD

**Issue by annhilati** [Vertretungsapp/app#261]
Ich finde aktuell, dass man in der Stundenansicht, Lehrer und Fach zu schlecht unterscheiden kann. Vielleicht könnte man beim Lehrer eine dünnere Version der Font benutzen

**Comment by SachsenspieltCoding** [comment]
Schau mal in diese Version, ob das so passt 
https://app-git-issue-261-vertretungsapp.vercel.app/

**Comment by annhilati** [comment]
Ich glaube optimal ist es noch nicht, und es macht das Design ein wenig kaputt, aber geht in eine gute Richtung. Ich denke mal, weiter experimentieren

**Comment by SachsenspieltCoding** [comment]
Meinst du, man könnte noch mit grautönen arbeiten?

**Comment by annhilati** [comment]
Auf jeden Fall. Gute Idee

**Comment by SachsenspieltCoding** [comment]
![Bildschirmfoto am 2024-08-02 um 21 09 36](https://github.com/user-attachments/assets/3a0c6da6-c45d-4df5-b6b5-6b9ee9e0ef72)

Würde dann in so eine Richtung gehene

**Comment by annhilati** [comment]
Sehr gut

**Comment by SachsenspieltCoding** [comment]
@annhilati Die vorgeschlagene Änderung mit dem ausgegrautem ist jetzt auf dem Deploy Link oben verfügbar
