### ISSUE TITLE
Vertretungsdaten werden beim Aktualisieren durcheinandergewürfelt angezeigt

### ISSUE THREAD

**Issue by annhilati** [Vertretungsapp/app#280]
Wenn man bei aktivem Filter die Daten aktualisiert, kann es passieren, dass die Daten aus den Stunden komplett durcheinander geworfen werden, teilweise auch mit Stunden, die herausgefiltert sind.

## Falscher Zustand
![Screenshot_2024-08-05-20-41-46-763_com.android.chrome.jpg](https://github.com/user-attachments/assets/1f787dca-0a19-4f5e-884e-db6f6bbe8860)
![Screenshot_2024-08-05-20-41-52-993_com.android.chrome.jpg](https://github.com/user-attachments/assets/5b8321b6-f235-4cab-8153-4dc477e196ac)
![Screenshot_2024-08-05-20-41-55-812_com.android.chrome.jpg](https://github.com/user-attachments/assets/5571caa4-a338-4e7e-ba1e-c05024e92db2)

Wenn man dann auf einen anderen Tag und wieder zurück wechselt ist das Problem behoben:

## Richtiger Zustand
![Screenshot_2024-08-05-20-42-35-013_com.android.chrome.jpg](https://github.com/user-attachments/assets/0d1124f0-4279-4595-bd04-09fe54aa3fb2)
![Screenshot_2024-08-05-20-42-37-533_com.android.chrome.jpg](https://github.com/user-attachments/assets/f1cff6c7-0965-41c8-ba1a-0c4a1fb9fddc)

Keine Ahnung, ob das zusammenhängt, aber das Problem wurde beobachtet kurz nachdem der Plan große inhaltliche Veränderungen erfahren hat (Problem mit dem Cache?). Bspw. sind neue zusatzInfo Elemente hinzugekommen.

**Comment by SachsenspieltCoding** [comment]
Ich glaube das ist eher ein SvelteKit Ding, dass der da mit den keys nicht hinterherkommt und die Elemente nicht vorher sauber aus der DOM nimmt.

Müsste man sich in Verbindung mit #279 anschauen

**Comment by SachsenspieltCoding** [comment]
> [!NOTE]
> Der Fehler tritt auf, wenn man einen Plan zweimal hintereinander aktualisiert.

**Comment by annhilati** [comment]
Kann man hiergegen etwas machen?

**Comment by SachsenspieltCoding** [comment]
Das Problem ist bereits identifiziert und wird bald behoben. Wahrscheinlich gibt es hierzu sogar noch ein vorgezogenes Update.

Ab nächster Woche sollte das nicht mehr auftreten
