### ISSUE TITLE
App komplett leer

### ISSUE THREAD

**Issue by annhilati** [Vertretungsapp/app#281]
Auf einem Gerät, dass das selbe Modell ist, wie eines Geräts, wo die App definitiv funktioniert, ist die App komplett weiß. Egal ob PWA oder Website. Auch das löschen der Websitedaten bringt nichts.
Noch gestern hat alles wie gewollt funktioniert.

Mi 11 Lite
Android 14
HyperOS
Chrome

**Comment by SachsenspieltCoding** [comment]
Hm, das ist komisch. Im Error Monitoring ist auch nichts aufgelaufen...

**Comment by SachsenspieltCoding** [comment]
Inwiefern hat die App vorher funktioniert?

**Comment by annhilati** [comment]
Anmelden, Klassen und Stunden einsehen, Einstellungen ändern und speichern

Pretty much alles

**Comment by SachsenspieltCoding** [comment]
Besteht das Problem immer noch?
Gibt es noch irgendwelche Anhaltspunkte, um das ganze zu reproduzieren? Ich weiß echt nicht, woran das liegt

**Comment by SachsenspieltCoding** [comment]
@annhilati ?

**Comment by SachsenspieltCoding** [comment]
Da sich hier keiner mehr gemeldet hat, schließe ich dann mal das Issue
