### ISSUE TITLE
Info-Blöcke sollten pro Tag zusammengefasst werden

### ISSUE THREAD

**Issue by SachsenspieltCoding** [Vertretungsapp/app#285]
Wenn eine IfZeile in den allgemeinen Planinformationen keinen Inhalt hat, sollte diese von der App herausgefiltert werden.

**Comment by annhilati** [comment]
Nicht unbedingt. Bei uns ist es so, dass mit den Zeilen mehrteiliges Texte gemacht werden. Vielmehr ist es aktuell so, dass bei uns die Information eines Tages auseinandergeschnitten angezeigt wird

**Comment by annhilati** [comment]
Genau
