### ISSUE TITLE
ZusatzInfo auch unter den Plänen anzeigen 

### ISSUE THREAD

**Issue by annhilati** [Vertretungsapp/app#294]
Aufgrund der Gewöhnung an die VpMobil24 App fänd ich es cool, wenn die ZusatzInfo der ganzen Schule unter jedem Plan, vor allem den der Klassen, angezeigt würde. Man kann ja einen Toggle dafür implementieren

**Comment by SachsenspieltCoding** [comment]
Erachte ich für nicht sinnvoll bzw. ist dies nicht mit der Vision der Vertretungsapp kompatibel
